// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpweXHUaTj0BZP_uCnKXjJ6puV8FmWRfc',
    appId: '1:356570140700:web:127396513dcfae0918cfd9',
    messagingSenderId: '356570140700',
    projectId: 'evenly-app-route-academy',
    authDomain: 'evenly-app-route-academy.firebaseapp.com',
    storageBucket: 'evenly-app-route-academy.firebasestorage.app',
    measurementId: 'G-RSMM2D5LKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK1CGnhtx1Qqpkkru8ZNapAk_HOVQlYyk',
    appId: '1:356570140700:android:0117a65e1549520018cfd9',
    messagingSenderId: '356570140700',
    projectId: 'evenly-app-route-academy',
    storageBucket: 'evenly-app-route-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ18j6A9OEo4z0lgqbEDnF-mjwB2RF4I8',
    appId: '1:356570140700:ios:411af84be22b7e3f18cfd9',
    messagingSenderId: '356570140700',
    projectId: 'evenly-app-route-academy',
    storageBucket: 'evenly-app-route-academy.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ18j6A9OEo4z0lgqbEDnF-mjwB2RF4I8',
    appId: '1:356570140700:ios:411af84be22b7e3f18cfd9',
    messagingSenderId: '356570140700',
    projectId: 'evenly-app-route-academy',
    storageBucket: 'evenly-app-route-academy.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpweXHUaTj0BZP_uCnKXjJ6puV8FmWRfc',
    appId: '1:356570140700:web:410f0cff103e243c18cfd9',
    messagingSenderId: '356570140700',
    projectId: 'evenly-app-route-academy',
    authDomain: 'evenly-app-route-academy.firebaseapp.com',
    storageBucket: 'evenly-app-route-academy.firebasestorage.app',
    measurementId: 'G-F0D2ZFTH6M',
  );

}